version: "3.7"
services:

  mongo:
    env_file:
      - .env
    image: mongo
    restart: on-failure
    ports:
    - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
    - mongodata:/data/db

  mongo-express:
    env_file:
      - .env
    image: mongo-express
    depends_on:
      - mongo
    restart: on-failure
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_LOGIN}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_LOGIN}:${MONGO_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: 0

  redis:
    image: redis
    env_file:
      - .env
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379
    networks:
      - profi-net

networks:
  profi-net:
    external:
      name: profi-network

volumes:
  redisdata:
    name: redis-pr
    external: true
  mongodata:
    name: mngdb-pr
    external: true

